# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchgit {
      url = "https://github.com/Hejsil/zig-clap";
      rev = "5289e0753cd274d65344bef1c114284c633536ea";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "toml-0.3.0-bV14BfV7AQD8DkuQI7skP8ekQTaBYKTO0MY_35Cw_EXo";
    path = fetchgit {
      url = "https://github.com/sam701/zig-toml";
      rev = "475b03c630c802f8b6bd3e239d8fc2279b4fadb8";
      hash = "sha256-TOW27uDzos3P0K3535TYxogR1o2j5u2BaMHo9vyAbW8=";
    };
  }
]
